# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: gd
    loaders: 
        default:
            filesystem:
                locator: filesystem
                data_root:
                    - 'C:\laragon\www\sfUpnCom\upncom/public'
                allow_unresolvable_data_roots: false
                bundle_resources:
                    enabled: false
                    access_control_type: blacklist
                    access_control_list: {  }
    resolvers:
        default:
            web_path:
                web_root: 'C:\laragon\www\sfUpnCom\upncom/public'
                cache_prefix: media/cache
    cache: default
    cache_base_path: ''
    data_loader: default
    default_image: null
    default_filter_set_settings:
        quality: 100
        jpeg_quality: null
        png_compression_level: null
        png_compression_filter: null
        format: null
        animated: false
        cache: null
        data_loader: null
        default_image: null
        filters: {  }
        post_processors: {  }
    controller:
        filter_action: 'Liip\ImagineBundle\Controller\ImagineController::filterAction'
        filter_runtime_action: 'Liip\ImagineBundle\Controller\ImagineController::filterRuntimeAction'
        redirect_response_code: 302
    filter_sets: {  }
    twig:
        mode: legacy
        assets_version: null
    enqueue: false
    messenger:
        enabled: false
    templating: true
    webp:
        generate: true
        quality: 90
        cache: null
        data_loader: null
        post_processors: {  }