vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /img/upload
            upload_destination: '%kernel.project_dir%/public/img/upload'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
